import type { InsertParentingTip } from "@shared/schema";

export const parentingTipsSeed: InsertParentingTip[] = [
  // NEWBORN (0-3 months)
  {
    title: "The Power of Skin-to-Skin Contact",
    content: "Skin-to-skin contact, also called kangaroo care, provides incredible benefits for newborns. Hold your baby against your bare chest for at least 20 minutes daily. This regulates their body temperature, heart rate, and breathing while releasing oxytocin in both parent and baby. It strengthens bonding and can help with breastfeeding success.",
    excerpt: "Discover why holding your baby skin-to-skin is one of the most powerful things you can do.",
    category: "development",
    ageMinMonths: "0",
    ageMaxMonths: "6",
    author: "PeacePad Team",
    tags: ["bonding", "newborn care", "development"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Understanding Your Baby's Sleep Patterns",
    content: "Newborns sleep 14-17 hours per day but in short bursts of 2-4 hours. This is completely normal and necessary for their brain development. Create a calm sleep environment with dim lights and white noise. Watch for sleep cues like yawning, eye rubbing, and fussiness. Don't worry about creating 'bad habits' right now - focus on meeting your baby's needs.",
    excerpt: "Why newborn sleep seems chaotic - and what's actually normal.",
    category: "health",
    ageMinMonths: "0",
    ageMaxMonths: "4",
    author: "PeacePad Team",
    tags: ["sleep", "newborn", "health"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Co-Parenting in the First Weeks",
    content: "The early weeks with a newborn can be overwhelming for both parents. Communicate openly about who handles night feeds, diaper changes, and household tasks. Take shifts to ensure both parents get adequate rest. Remember, you're on the same team. If tensions arise, step back and remind yourselves that sleep deprivation affects everyone's patience.",
    excerpt: "How to work together as a team during the challenging newborn phase.",
    category: "co-parenting",
    ageMinMonths: "0",
    ageMaxMonths: "6",
    author: "PeacePad Team",
    tags: ["co-parenting", "teamwork", "newborn"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },

  // INFANT (4-11 months)
  {
    title: "Starting Solid Foods Safely",
    content: "Most babies are ready for solid foods around 6 months when they can sit with support and show interest in food. Start with single-ingredient purees like sweet potato, avocado, or banana. Introduce one new food every 3-4 days to watch for allergies. Current research suggests early introduction of common allergens (peanut, egg, fish) may actually reduce allergy risk.",
    excerpt: "A gentle guide to introducing your baby's first foods.",
    category: "nutrition",
    ageMinMonths: "4",
    ageMaxMonths: "12",
    author: "PeacePad Team",
    tags: ["solid foods", "feeding", "nutrition", "allergies"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Encouraging Motor Development",
    content: "Give your baby plenty of supervised tummy time to strengthen neck and arm muscles. Place colorful toys just out of reach to encourage reaching and eventually crawling. Create a safe floor space for exploration. Every baby develops at their own pace - some skip crawling entirely and go straight to walking, which is perfectly normal.",
    excerpt: "Simple ways to support your baby's physical milestones.",
    category: "development",
    ageMinMonths: "4",
    ageMaxMonths: "12",
    author: "PeacePad Team",
    tags: ["motor skills", "tummy time", "crawling", "milestones"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Creating a Safe Play Environment",
    content: "As your baby becomes mobile, childproofing becomes essential. Cover electrical outlets, secure furniture to walls, use baby gates at stairs, and keep small objects out of reach. Get on the floor at baby's eye level to spot potential hazards. Lock cabinets with cleaning supplies and medications. A safe environment lets your baby explore freely.",
    excerpt: "Essential safety measures as your baby starts to move.",
    category: "safety",
    ageMinMonths: "6",
    ageMaxMonths: "18",
    author: "PeacePad Team",
    tags: ["safety", "childproofing", "baby proofing"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },

  // TODDLER (1-2 years)
  {
    title: "Managing Toddler Tantrums",
    content: "Tantrums are a normal part of toddler development - their emotions are big but their ability to regulate them is still developing. Stay calm (even when it's hard), validate their feelings, and offer comfort. Avoid giving in to unreasonable demands or punishing tantrums. Instead, wait for the storm to pass, then help them name their feelings. 'You were really frustrated when I said no cookie.'",
    excerpt: "Why tantrums happen and how to handle them with patience.",
    category: "discipline",
    ageMinMonths: "12",
    ageMaxMonths: "48",
    author: "PeacePad Team",
    tags: ["tantrums", "emotions", "discipline", "toddler"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Encouraging Language Development",
    content: "Toddlers learn language by hearing it constantly. Narrate your day: 'Now we're putting on your shoes. These are your blue shoes!' Read books together daily, pointing at pictures and asking questions. Expand on their words - if they say 'dog,' you say 'Yes, that's a big brown dog!' Limit screen time as face-to-face interaction is crucial for language development.",
    excerpt: "Simple strategies to boost your toddler's vocabulary.",
    category: "development",
    ageMinMonths: "12",
    ageMaxMonths: "36",
    author: "PeacePad Team",
    tags: ["language", "talking", "reading", "development"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Transitioning Between Two Homes",
    content: "Toddlers thrive on routine and may struggle with transitions between co-parent homes. Keep a consistent goodbye ritual, pack a comfort item that travels with them, and maintain similar bedtime routines at both homes. Avoid lengthy goodbyes which can increase anxiety. Stay positive about the other parent - your toddler picks up on your emotions.",
    excerpt: "Helping your toddler adjust to two-home living.",
    category: "co-parenting",
    ageMinMonths: "12",
    ageMaxMonths: "48",
    author: "PeacePad Team",
    tags: ["transitions", "two homes", "co-parenting", "routine"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Healthy Eating for Picky Toddlers",
    content: "Toddler pickiness is developmentally normal. Offer a variety of healthy options without pressure. It can take 10-15 exposures before a child accepts a new food. Make mealtimes low-stress, avoid using dessert as a reward, and model healthy eating yourself. Let them explore food with their hands - sensory play with food reduces food fears.",
    excerpt: "Strategies for navigating the picky eating phase.",
    category: "nutrition",
    ageMinMonths: "12",
    ageMaxMonths: "48",
    author: "PeacePad Team",
    tags: ["picky eating", "nutrition", "meals", "toddler"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },

  // PRESCHOOL (3-5 years)
  {
    title: "Building Emotional Intelligence",
    content: "Preschoolers are ready to learn about emotions. Use books, puppets, and everyday moments to teach feeling words. 'Your friend looks sad because you took their toy. How do you think that feels?' Practice deep breathing for calm-down strategies. Create a feelings chart they can point to. Validate all emotions while setting limits on behavior: 'It's okay to feel angry, but it's not okay to hit.'",
    excerpt: "Teaching your preschooler to understand and express feelings.",
    category: "social-skills",
    ageMinMonths: "36",
    ageMaxMonths: "72",
    author: "PeacePad Team",
    tags: ["emotions", "EQ", "feelings", "social skills"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Preparing for Kindergarten",
    content: "Kindergarten readiness isn't just about academics. Focus on independence skills: using the bathroom alone, putting on shoes, opening lunch containers. Practice following multi-step instructions and taking turns. Read together daily and practice writing their name. Visit the school beforehand if possible. Most importantly, build confidence by emphasizing what they CAN do.",
    excerpt: "Skills your child needs before starting school.",
    category: "education",
    ageMinMonths: "48",
    ageMaxMonths: "72",
    author: "PeacePad Team",
    tags: ["kindergarten", "school readiness", "education"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "The Power of Imaginative Play",
    content: "Pretend play is critical brain development, not just fun. When children play house, doctor, or superhero, they're developing problem-solving, language, social skills, and emotional regulation. Join their play without taking over - let them lead the story. Provide simple props (cardboard boxes, dress-up clothes) that encourage creativity rather than prescriptive toys.",
    excerpt: "Why imaginative play matters more than you might think.",
    category: "development",
    ageMinMonths: "24",
    ageMaxMonths: "84",
    author: "PeacePad Team",
    tags: ["play", "imagination", "creativity", "development"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Positive Discipline for Preschoolers",
    content: "Replace punishment with teaching. Instead of 'Go to your room!' try 'Let's take a break together until you feel calm.' Give choices: 'Do you want to put on your coat or your shoes first?' Use natural consequences when safe: 'If you throw the toy, the toy goes away.' Catch them being good and praise specifically: 'I noticed you shared with your sister. That was kind!'",
    excerpt: "Effective discipline strategies that build connection.",
    category: "discipline",
    ageMinMonths: "36",
    ageMaxMonths: "72",
    author: "PeacePad Team",
    tags: ["discipline", "positive parenting", "behavior"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Consistent Rules Across Two Homes",
    content: "Children do best when both homes have similar expectations around safety and behavior. Focus on aligning the big things: screen time limits, bedtime routines, homework expectations. Accept that some differences are okay - kids can adapt to different household styles. Communicate respectfully about what's working. Use a co-parenting app to share updates without conflict.",
    excerpt: "Creating consistency while respecting household differences.",
    category: "co-parenting",
    ageMinMonths: "36",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["consistency", "rules", "co-parenting", "communication"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },

  // SCHOOL AGE (6-12 years)
  {
    title: "Homework Without the Battles",
    content: "Create a consistent homework routine: same time, same place, with supplies ready. Be available but don't do the work for them - ask guiding questions instead. Break large projects into smaller tasks. If homework consistently takes too long or causes meltdowns, communicate with the teacher. Remember that some struggle is part of learning, but excessive frustration isn't helpful.",
    excerpt: "Strategies for making homework time smoother.",
    category: "education",
    ageMinMonths: "72",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["homework", "school", "education", "routine"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Navigating Friendships and Peer Pressure",
    content: "School-age kids increasingly care about peer acceptance. Help them develop the confidence to be themselves while fitting in. Role-play how to handle peer pressure. Ask open-ended questions about their friends without interrogating. Teach them it's okay to have different friends for different activities. If they're struggling socially, consider activities outside school where they can find their 'tribe.'",
    excerpt: "Supporting your child's social world.",
    category: "social-skills",
    ageMinMonths: "72",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["friendships", "peer pressure", "social skills"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Fostering a Growth Mindset",
    content: "Praise effort, not just results: 'You worked really hard on that!' instead of 'You're so smart!' Normalize mistakes as part of learning. Share your own struggles and how you overcame them. When they say 'I can't do this,' add 'yet': 'You can't do it YET. Let's figure out what to try next.' A growth mindset builds resilience that serves them throughout life.",
    excerpt: "Teaching your child that abilities can be developed.",
    category: "development",
    ageMinMonths: "60",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["growth mindset", "resilience", "learning", "confidence"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Screen Time Balance",
    content: "Quality matters more than quantity. Choose educational content and co-view when possible. Set clear limits and use parental controls. Keep devices out of bedrooms and off during meals. Balance screen time with physical activity, reading, and face-to-face interaction. Be a role model - kids notice when parents are always on their phones too.",
    excerpt: "Finding healthy balance in a digital world.",
    category: "health",
    ageMinMonths: "36",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["screen time", "technology", "digital wellness", "balance"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Talking to Kids About Divorce or Separation",
    content: "Be honest in age-appropriate ways. Reassure them it's not their fault and both parents still love them. Avoid badmouthing the other parent - this puts kids in the middle. Allow them to express all their feelings without judgment. Keep as much routine as possible. Consider family counseling if your child is really struggling. Answer questions honestly but don't overshare adult details.",
    excerpt: "Supporting your child through family changes.",
    category: "co-parenting",
    ageMinMonths: "48",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["divorce", "separation", "co-parenting", "emotions"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Building Responsibility with Chores",
    content: "Age-appropriate chores build life skills, responsibility, and family contribution. Start with simple tasks: making beds, clearing plates, feeding pets. Create a visual chore chart. Teach skills before expecting independence. Avoid paying for basic family contributions - these build character, not income. Praise effort and don't redo their work in front of them.",
    excerpt: "Why chores matter and how to implement them.",
    category: "discipline",
    ageMinMonths: "48",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["chores", "responsibility", "life skills"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },

  // TEEN (13-17 years)
  {
    title: "Staying Connected with Your Teen",
    content: "Teens may push away but still need connection. Find activities you can do together - even if it's just driving them places. Stay curious without being nosy. Listen more than you lecture. Know their friends and create a welcoming home. Have phone-free family dinners. Remember: their brain is literally under construction, especially the decision-making parts.",
    excerpt: "Maintaining your relationship through the teenage years.",
    category: "development",
    ageMinMonths: "144",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["teens", "connection", "communication", "adolescence"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Supporting Teen Mental Health",
    content: "Watch for warning signs: persistent sadness, withdrawal, sleep changes, declining grades, or talk of self-harm. Create a judgment-free zone for conversations. Normalize seeking help - therapy is just like going to the doctor for physical health. If they're resistant to talking to you, offer other trusted adults. Model self-care and emotional expression yourself.",
    excerpt: "Recognizing struggles and knowing when to seek help.",
    category: "health",
    ageMinMonths: "144",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["mental health", "teens", "depression", "anxiety", "support"],
    readTimeMinutes: "5",
    publishedAt: new Date(),
  },
  {
    title: "Setting Boundaries with Teen Technology",
    content: "Teens need guidance, not surveillance. Create a family media agreement together. Keep devices charging outside bedrooms at night. Use parental controls but also have ongoing conversations about online safety. Know their passwords but respect their privacy unless there's a safety concern. Teach digital citizenship - what they post follows them.",
    excerpt: "Navigating technology with teenagers.",
    category: "safety",
    ageMinMonths: "144",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["technology", "safety", "teens", "boundaries", "online safety"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Co-Parenting a Teenager",
    content: "Teens often try to play parents against each other. Stay united on big issues while respecting that each home has its own style. Communicate directly with your co-parent rather than through your teen. Let your teen have a voice in scheduling without making them the decision-maker. Support their relationship with both parents even if it's complicated for you.",
    excerpt: "Working together when your teen pushes boundaries.",
    category: "co-parenting",
    ageMinMonths: "144",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["co-parenting", "teens", "communication", "boundaries"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Preparing Teens for Independence",
    content: "Use the teen years to gradually increase responsibility. Teach life skills: cooking, laundry, budgeting, car maintenance. Let them make (safe) mistakes and experience natural consequences. Discuss goals for after high school. Give increasing independence while keeping connection. The goal is a competent young adult who still wants to come home.",
    excerpt: "Building the skills your teen needs for adulthood.",
    category: "development",
    ageMinMonths: "168",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["independence", "life skills", "teens", "adulting"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },

  // ALL AGES
  {
    title: "The Importance of Routine",
    content: "Children of all ages thrive with predictable routines. Morning routines prevent chaos, bedtime routines improve sleep, and after-school routines reduce homework battles. Visual schedules help younger kids know what to expect. Be flexible when needed, but consistent most of the time. Routines reduce anxiety and power struggles.",
    excerpt: "How consistent routines benefit children at every age.",
    category: "development",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["routine", "structure", "predictability", "all ages"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Quality Time Over Quantity",
    content: "Ten minutes of focused, device-free attention beats an hour of distracted presence. Get on the floor with them. Make eye contact. Follow their lead in play. Create small rituals: reading before bed, Saturday pancakes, walks together. These moments build connection and create lasting memories.",
    excerpt: "Making the most of your time together.",
    category: "development",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["quality time", "connection", "presence", "bonding"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Modeling the Behavior You Want",
    content: "Children learn more from what you do than what you say. If you want them to manage anger, show them how you calm down. If you want them to be kind, let them see you being kind to others - including their other parent. Apologize when you make mistakes. Your actions are their blueprint for behavior.",
    excerpt: "You are your child's most important teacher.",
    category: "discipline",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["modeling", "behavior", "example", "parenting"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Healthy Sleep Habits",
    content: "Sleep affects everything: mood, behavior, learning, and health. Maintain consistent sleep and wake times, even on weekends. Create a calming bedtime routine. Keep bedrooms cool, dark, and screen-free. Watch for signs of sleep deprivation: irritability, difficulty focusing, frequent illness. Most children need more sleep than parents realize.",
    excerpt: "Why sleep matters and how to protect it.",
    category: "health",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["sleep", "health", "bedtime", "routine"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Effective Co-Parent Communication",
    content: "Keep communication focused on the child, not past hurts. Use 'I' statements and avoid blame. Stick to facts and logistics. Use written communication (text, app) for documentation and to reduce conflict. Establish boundaries about response times. Remember: you're business partners in parenting. Keep it professional.",
    excerpt: "Communicating effectively with your co-parent.",
    category: "co-parenting",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["communication", "co-parenting", "conflict resolution"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Building Your Child's Self-Esteem",
    content: "Self-esteem comes from competence, not constant praise. Let them struggle appropriately before helping. Celebrate effort and progress. Avoid comparing them to siblings or peers. Give them real responsibilities. Listen to their opinions. Love them unconditionally while setting clear limits. Confidence grows from overcoming challenges, not avoiding them.",
    excerpt: "Nurturing genuine confidence in your child.",
    category: "development",
    ageMinMonths: "24",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["self-esteem", "confidence", "development", "parenting"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Reading Together at Every Age",
    content: "Reading together builds vocabulary, comprehension, empathy, and connection. Even after children can read independently, reading aloud together has benefits. For babies: board books and point-and-name. For toddlers: predictable stories with repetition. For older kids: chapter books at bedtime. For teens: discuss books you're both reading.",
    excerpt: "Why reading together never loses its magic.",
    category: "education",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["reading", "literacy", "books", "connection"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Family Meals Matter",
    content: "Regular family meals (even just a few per week) are linked to better nutrition, higher grades, reduced risk behaviors in teens, and stronger family bonds. Focus on connection, not perfection. Keep meals device-free. Use conversation starters. Let kids help with age-appropriate tasks. It doesn't have to be dinner - breakfast counts too.",
    excerpt: "The surprising power of eating together.",
    category: "nutrition",
    ageMinMonths: "12",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["family meals", "nutrition", "connection", "dinner"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Outdoor Play and Nature",
    content: "Time outdoors reduces anxiety, improves focus, and benefits physical health. Aim for at least an hour of outdoor play daily when possible. Let them get dirty and take reasonable risks. Nature exploration doesn't require equipment - just time and attention. Regular outdoor time is linked to better sleep and reduced screen dependency.",
    excerpt: "The benefits of getting outside together.",
    category: "health",
    ageMinMonths: "6",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["outdoor play", "nature", "physical activity", "health"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "When to Seek Professional Help",
    content: "Parenting is hard, and sometimes you need extra support. Consider professional help if your child shows persistent sadness or anxiety, behavioral problems that interfere with daily life, regression in development, or if you're feeling overwhelmed. Seeking help is a sign of strength, not weakness. Start with your pediatrician for referrals.",
    excerpt: "Recognizing when extra support is needed.",
    category: "health",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["mental health", "therapy", "support", "professional help"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Creating Traditions",
    content: "Family traditions build identity and create lasting memories. They don't have to be elaborate - Friday pizza night, birthday breakfast in bed, or annual photo at the same spot each year. Traditions provide stability during times of change. In co-parenting situations, each home can have its own special traditions.",
    excerpt: "Building meaningful family rituals.",
    category: "development",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["traditions", "family rituals", "memories", "connection"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Physical Affection at Every Age",
    content: "Physical touch remains important throughout childhood. Babies need constant holding, toddlers need cuddles, school-age kids benefit from hugs and high-fives, and even teens (who may act resistant) need affection. Follow their lead on what feels comfortable. Daily doses of appropriate physical affection support emotional development.",
    excerpt: "Why your child needs hugs at every stage.",
    category: "development",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["physical affection", "hugs", "touch", "connection"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Teaching Conflict Resolution",
    content: "Children learn to handle disagreements by watching you. Teach them to use 'I feel' statements, take turns talking, look for win-win solutions, and know when to walk away. Role-play common scenarios. When they fight with siblings or friends, guide them through resolution rather than immediately separating or solving it yourself.",
    excerpt: "Skills for handling disagreements peacefully.",
    category: "social-skills",
    ageMinMonths: "36",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["conflict resolution", "social skills", "communication", "problem solving"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Celebrating Differences in Parenting Styles",
    content: "Co-parents don't have to agree on everything. Different parenting styles can actually benefit children by teaching flexibility. Focus on aligning on safety, major values, and health issues. Accept that one home might be more structured while another is more relaxed. Your child can thrive with both approaches.",
    excerpt: "Embracing that different can still be good.",
    category: "co-parenting",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["parenting styles", "co-parenting", "differences", "flexibility"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "The Gift of Boredom",
    content: "Resist the urge to constantly entertain your child. Boredom sparks creativity and self-directed play. When they complain of boredom, suggest they find something to do rather than providing instant solutions. Provide open-ended toys (blocks, art supplies, dress-up clothes) and let them figure out how to use them.",
    excerpt: "Why unstructured time is valuable.",
    category: "development",
    ageMinMonths: "24",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["boredom", "creativity", "play", "independence"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Managing Parental Stress",
    content: "You can't pour from an empty cup. Make time for self-care, even if it's just 10 minutes of quiet. Ask for help when you need it. Stay connected with adult friends. Watch your own stress levels - children are remarkably attuned to parental anxiety. Your wellbeing directly impacts your parenting.",
    excerpt: "Taking care of yourself so you can care for them.",
    category: "health",
    ageMinMonths: "0",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["self-care", "stress", "parental wellbeing", "mental health"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Handling Sibling Rivalry",
    content: "Sibling conflict is normal and can actually teach valuable skills. Avoid always playing referee - let them work out minor disputes. Never compare children to each other. Celebrate each child's unique strengths. Make one-on-one time with each child a priority. When conflicts escalate, help them use 'I feel' statements rather than taking sides.",
    excerpt: "Turning sibling battles into learning opportunities.",
    category: "discipline",
    ageMinMonths: "24",
    ageMaxMonths: "168",
    author: "PeacePad Team",
    tags: ["siblings", "conflict", "discipline", "family dynamics"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Potty Training Without Stress",
    content: "Wait until your child shows readiness signs: staying dry for longer periods, showing interest in the toilet, disliking wet diapers. Avoid pressure and power struggles - this should be their accomplishment, not yours. Celebrate successes without overdoing it. Accept accidents calmly. Most children are fully trained between 2-4 years, and that's a wide range of normal.",
    excerpt: "A relaxed approach to this important milestone.",
    category: "development",
    ageMinMonths: "18",
    ageMaxMonths: "48",
    author: "PeacePad Team",
    tags: ["potty training", "toilet training", "milestones", "toddler"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Supporting Kids Through Change",
    content: "Children process change differently than adults. Give plenty of warning before transitions when possible. Maintain routines as anchors of stability. Allow them to express all feelings about the change. Read books about similar situations. Create a sense of control by letting them make small choices. Your calm confidence helps them feel secure.",
    excerpt: "Helping children adapt to life's transitions.",
    category: "development",
    ageMinMonths: "24",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["change", "transitions", "moving", "new school", "coping"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Teaching Kids About Money",
    content: "Start early with age-appropriate lessons. Use clear jars for saving, spending, and giving so they can see money grow. Pay allowance (tied to chores or not - both approaches work) to give hands-on practice. Let them make mistakes with small amounts. Talk about your own financial decisions in kid-friendly terms. Open a savings account together.",
    excerpt: "Building financial literacy from an early age.",
    category: "education",
    ageMinMonths: "48",
    ageMaxMonths: "168",
    author: "PeacePad Team",
    tags: ["money", "allowance", "financial literacy", "saving"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Making Doctor Visits Easier",
    content: "Prepare children for what to expect without overpromising it won't hurt. Bring comfort items. Practice playing doctor at home. Stay calm yourself - children mirror your anxiety. Distraction during procedures can help. Ask if you can hold younger children during shots. Afterward, acknowledge their bravery and do something enjoyable together.",
    excerpt: "Reducing anxiety around medical appointments.",
    category: "health",
    ageMinMonths: "12",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["doctor", "medical visits", "anxiety", "health"],
    readTimeMinutes: "3",
    publishedAt: new Date(),
  },
  {
    title: "Building Resilience in Children",
    content: "Resilience isn't about shielding children from difficulty - it's about teaching them to cope. Allow them to experience age-appropriate struggles and natural consequences. Model your own problem-solving. Avoid rushing to fix every problem. Teach that failure is part of learning. Maintain strong family connections as a safety net. Celebrate perseverance, not just success.",
    excerpt: "Raising children who can bounce back from challenges.",
    category: "development",
    ageMinMonths: "36",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["resilience", "coping", "problem solving", "failure"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Bedtime Routines That Work",
    content: "A consistent bedtime routine signals the brain it's time to sleep. Start 30-60 minutes before sleep time with calming activities: bath, pajamas, teeth brushing, stories, songs. Keep the order the same each night. Dim lights and reduce stimulation. Use a calm, warm voice. If bedtime battles occur, stay consistent but compassionate. Avoid screens for at least an hour before bed.",
    excerpt: "Creating peaceful transitions to sleep.",
    category: "health",
    ageMinMonths: "6",
    ageMaxMonths: "120",
    author: "PeacePad Team",
    tags: ["bedtime", "sleep", "routine", "night time"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Talking to Kids About Difficult Topics",
    content: "Children can handle more truth than we often think - what they can't handle is being lied to or kept in the dark. Answer questions honestly at their developmental level. It's okay to say 'I don't know' or 'I need to think about how to explain this.' Follow their lead on how much detail they want. Create an open environment where no question is off-limits.",
    excerpt: "Having honest conversations about hard subjects.",
    category: "development",
    ageMinMonths: "48",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["difficult conversations", "honesty", "communication", "death", "divorce"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Limiting Power Struggles",
    content: "Most power struggles aren't worth winning. Ask yourself: Is this a safety issue or a preference issue? Offer choices within limits: 'Red shirt or blue shirt?' Pick your battles wisely. Use 'when/then' statements: 'When you finish dinner, then you can have dessert.' Give warnings before transitions. Avoid arguing - state the rule once and follow through.",
    excerpt: "Strategies for reducing daily battles.",
    category: "discipline",
    ageMinMonths: "18",
    ageMaxMonths: "144",
    author: "PeacePad Team",
    tags: ["power struggles", "discipline", "choices", "toddler"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
  {
    title: "Encouraging Healthy Eating Habits",
    content: "Your job is to offer healthy options; their job is to decide how much to eat. Avoid short-order cooking - offer what the family is eating. Include at least one food you know they'll eat at each meal. Let them serve themselves when possible. Eat together as often as you can. Avoid labeling foods as 'good' or 'bad.' Trust their hunger and fullness cues.",
    excerpt: "Building a healthy relationship with food.",
    category: "nutrition",
    ageMinMonths: "12",
    ageMaxMonths: "216",
    author: "PeacePad Team",
    tags: ["nutrition", "healthy eating", "meals", "picky eating"],
    readTimeMinutes: "4",
    publishedAt: new Date(),
  },
];

export async function seedParentingTips() {
  console.log("Seeding parenting tips...");
  
  try {
    const { storage } = await import("./storage");
    const existing = await storage.getParentingTips();
    if (existing.length > 0) {
      console.log(`Found ${existing.length} existing parenting tips. Skipping seed.`);
      return;
    }

    for (const tip of parentingTipsSeed) {
      await storage.createParentingTip(tip);
    }

    console.log(`Successfully seeded ${parentingTipsSeed.length} parenting tips!`);
  } catch (error: any) {
    if (error.message?.includes('disabled') || error.message?.includes('suspended')) {
      console.log('[Seed Tips] Database suspended - tips will be seeded when database wakes up');
    } else {
      console.error("Error seeding parenting tips:", error);
    }
  }
}
