/**
 * Document Template Registry
 * Defines document types, templates, and generation logic for live documents
 * D1 implements: Inquiry Form, Proposal, Kickoff Document
 */

const DOCUMENT_TYPES = {
  INQUIRY_FORM: "inquiry_form",
  PROPOSAL: "proposal",
  KICKOFF: "kickoff"
};

const DOCUMENT_TEMPLATES = {
  inquiry_form: {
    name: "Inquiry Form",
    docType: "inquiry_form",
    description: "Initial discovery and project context capture",
    fields: [
      { key: "clientName", label: "Client Name", type: "text", required: true },
      { key: "projectTitle", label: "Project Title", type: "text", required: true },
      { key: "projectScope", label: "Project Scope", type: "textarea", required: true },
      { key: "objectives", label: "Primary Objectives", type: "textarea", required: false },
      { key: "timeline", label: "Timeline / Deadline", type: "text", required: false },
      { key: "budget", label: "Budget Range", type: "text", required: false },
      { key: "constraints", label: "Constraints or Risks", type: "textarea", required: false }
    ],
    renderer: (fields) => renderInquiryForm(fields)
  },

  proposal: {
    name: "Proposal",
    docType: "proposal",
    description: "Formal project proposal with scope, timeline, and deliverables",
    fields: [
      { key: "clientName", label: "Client Name", type: "text", required: true },
      { key: "projectTitle", label: "Project Title", type: "text", required: true },
      { key: "executiveSummary", label: "Executive Summary", type: "textarea", required: true },
      { key: "scope", label: "Scope of Work", type: "textarea", required: true },
      { key: "deliverables", label: "Deliverables", type: "textarea", required: true },
      { key: "timeline", label: "Timeline / Milestones", type: "textarea", required: false },
      { key: "investment", label: "Investment / Fee", type: "text", required: false },
      { key: "terms", label: "Terms & Conditions", type: "textarea", required: false }
    ],
    renderer: (fields) => renderProposal(fields)
  },

  kickoff: {
    name: "Kickoff Document",
    docType: "kickoff",
    description: "Project kickoff brief with team, approach, and next steps",
    fields: [
      { key: "clientName", label: "Client Name", type: "text", required: true },
      { key: "projectTitle", label: "Project Title", type: "text", required: true },
      { key: "projectGoal", label: "Project Goal", type: "textarea", required: true },
      { key: "teamMembers", label: "Team Members", type: "textarea", required: false },
      { key: "approach", label: "Approach & Methodology", type: "textarea", required: true },
      { key: "keyMilestones", label: "Key Milestones", type: "textarea", required: false },
      { key: "successCriteria", label: "Success Criteria", type: "textarea", required: false },
      { key: "nextSteps", label: "Immediate Next Steps", type: "textarea", required: true }
    ],
    renderer: (fields) => renderKickoff(fields)
  }
};

function renderInquiryForm(fields) {
  const safeField = (key) => String(fields?.[key] || "").trim();

  return `
# Inquiry Form

**Client:** ${safeField("clientName")}  
**Project:** ${safeField("projectTitle")}

## Project Scope
${safeField("projectScope")}

${safeField("objectives") ? `## Primary Objectives\n${safeField("objectives")}\n` : ""}
${safeField("timeline") ? `## Timeline / Deadline\n${safeField("timeline")}\n` : ""}
${safeField("budget") ? `## Budget Range\n${safeField("budget")}\n` : ""}
${safeField("constraints") ? `## Constraints or Risks\n${safeField("constraints")}\n` : ""}

---
*Generated by Una Labs ATEAM*
  `.trim();
}

function renderProposal(fields) {
  const safeField = (key) => String(fields?.[key] || "").trim();

  return `
# Proposal

**Client:** ${safeField("clientName")}  
**Project:** ${safeField("projectTitle")}

## Executive Summary
${safeField("executiveSummary")}

## Scope of Work
${safeField("scope")}

## Deliverables
${safeField("deliverables")}

${safeField("timeline") ? `## Timeline & Milestones\n${safeField("timeline")}\n` : ""}
${safeField("investment") ? `## Investment\n${safeField("investment")}\n` : ""}
${safeField("terms") ? `## Terms & Conditions\n${safeField("terms")}\n` : ""}

---
*Generated by Una Labs ATEAM*
  `.trim();
}

function renderKickoff(fields) {
  const safeField = (key) => String(fields?.[key] || "").trim();

  return `
# Project Kickoff

**Client:** ${safeField("clientName")}  
**Project:** ${safeField("projectTitle")}

## Project Goal
${safeField("projectGoal")}

${safeField("teamMembers") ? `## Team\n${safeField("teamMembers")}\n` : ""}

## Approach & Methodology
${safeField("approach")}

${safeField("keyMilestones") ? `## Key Milestones\n${safeField("keyMilestones")}\n` : ""}
${safeField("successCriteria") ? `## Success Criteria\n${safeField("successCriteria")}\n` : ""}

## Immediate Next Steps
${safeField("nextSteps")}

---
*Generated by Una Labs ATEAM*
  `.trim();
}

function autofillFromRun(run, docType) {
  const brief = run?.brief || {};
  const request = run?.request || {};
  const intake = request?.intake || {};

  const common = {
    clientName: run?.requestedBy || "",
    projectTitle: run?.title || brief?.title || ""
  };

  switch (normalizeDocType(docType)) {
    case "inquiry_form":
      return {
        ...common,
        projectScope: intake?.goal || brief?.primaryGoal || "",
        objectives: intake?.desiredOutput || "",
        timeline: "",
        budget: "",
        constraints: intake?.constraints || ""
      };

    case "proposal":
      return {
        ...common,
        executiveSummary: brief?.summary || intake?.goal || "",
        scope: intake?.goal || "",
        deliverables: run?.plan?.phases?.map((p) => p.title).join(", ") || "",
        timeline: run?.plan?.estimatedTimeline || "",
        investment: "",
        terms: ""
      };

    case "kickoff":
      return {
        ...common,
        projectGoal: brief?.primaryGoal || intake?.goal || "",
        teamMembers: "",
        approach: run?.plan?.summary || "",
        keyMilestones: run?.plan?.phases?.map((p) => p.title).join("\n- ") || "",
        successCriteria: brief?.successCriteria || "",
        nextSteps: run?.plan?.phases?.[0]?.title || ""
      };

    default:
      return common;
  }
}

function normalizeDocType(value = "") {
  const normalized = String(value || "").trim().toLowerCase();
  const valid = Object.values(DOCUMENT_TYPES);
  return valid.includes(normalized) ? normalized : DOCUMENT_TYPES.INQUIRY_FORM;
}

export {
  DOCUMENT_TYPES,
  DOCUMENT_TEMPLATES,
  autofillFromRun,
  normalizeDocType
};
