import type { SupportedLocale } from "./LocalizationProvider";

const copy = {
  en: { private: "Private", shared: "Shared with family", hide: "Hide", show: "Show", makePrivate: "Make private", share: "Share", shareCalendar: "Share this calendar?", shareBody: "Future events in this calendar will be visible to family participants.", confirmShare: "Confirm sharing", keepPrivate: "Keep private", addEvent: "Add event", eventTitle: "Event title", calendar: "Calendar", useCalendar: "Use {name} calendar", saveEvent: "Save event", deleteWarning: "Delete this event? Shared participants may lose access to it.", confirmDelete: "Confirm delete", cancel: "Cancel", deleteEvent: "Delete event", records: "Records", opening: "Opening Records", loading: "Loading your private Case Binders.", binders: "Your Case Binders", createBinder: "Create a Case Binder", binderBody: "Keep private records organized by family and child.", binderName: "Binder name", childLabel: "Child label", creating: "Creating...", create: "Create Case Binder", timeline: "Private timeline", noSources: "No sources linked yet.", message: "Message", calendarEvent: "Calendar event", timelineEntry: "{kind} timeline entry", linkMessage: "Link latest message", linkEvent: "Link next calendar event", attachment: "Prepare attachment details", fileName: "Original file name", mediaType: "Media type", fileSize: "File size in bytes", preparing: "Preparing...", prepare: "Prepare details", prepared: "Attachment details prepared", detailsPrepared: "Details prepared", noUpload: "No file was uploaded.", archive: "Archive Case Binder", tryAgain: "Try again", returnHome: "Return home", anotherTask: "Choose another task.", binderNameError: "Enter a Case Binder name.", childLabelError: "Enter a child label.", binderDetailsError: "Check the Case Binder details.", attachmentDetailsError: "Check the attachment details.", linkError: "PeacePad could not link this source." },
  fr: { private: "Privé", shared: "Partagé avec la famille", hide: "Masquer", show: "Afficher", makePrivate: "Rendre privé", share: "Partager", shareCalendar: "Partager ce calendrier?", shareBody: "Les futurs événements de ce calendrier seront visibles par les membres de la famille.", confirmShare: "Confirmer le partage", keepPrivate: "Garder privé", addEvent: "Ajouter un événement", eventTitle: "Titre de l’événement", calendar: "Calendrier", useCalendar: "Utiliser le calendrier {name}", saveEvent: "Enregistrer l’événement", deleteWarning: "Supprimer cet événement? Les participants pourraient ne plus y avoir accès.", confirmDelete: "Confirmer la suppression", cancel: "Annuler", deleteEvent: "Supprimer l’événement", records: "Dossiers", opening: "Ouverture des dossiers", loading: "Chargement de vos classeurs privés.", binders: "Vos classeurs", createBinder: "Créer un classeur", binderBody: "Organisez les dossiers privés par famille et par enfant.", binderName: "Nom du classeur", childLabel: "Identifiant de l’enfant", creating: "Création...", create: "Créer le classeur", timeline: "Chronologie privée", noSources: "Aucune source liée pour le moment.", message: "Message", calendarEvent: "Événement du calendrier", timelineEntry: "Entrée de chronologie : {kind}", linkMessage: "Lier le dernier message", linkEvent: "Lier le prochain événement", attachment: "Préparer les détails de la pièce jointe", fileName: "Nom du fichier original", mediaType: "Type de média", fileSize: "Taille du fichier en octets", preparing: "Préparation...", prepare: "Préparer les détails", prepared: "Détails de la pièce jointe préparés", detailsPrepared: "Détails préparés", noUpload: "Aucun fichier n’a été téléversé.", archive: "Archiver le classeur", tryAgain: "Réessayer", returnHome: "Retour à l’accueil", anotherTask: "Choisissez une autre tâche.", binderNameError: "Saisissez un nom de classeur.", childLabelError: "Saisissez un identifiant d’enfant.", binderDetailsError: "Vérifiez les détails du classeur.", attachmentDetailsError: "Vérifiez les détails de la pièce jointe.", linkError: "PeacePad n’a pas pu lier cette source." },
  es: { private: "Privado", shared: "Compartido con la familia", hide: "Ocultar", show: "Mostrar", makePrivate: "Hacer privado", share: "Compartir", shareCalendar: "¿Compartir este calendario?", shareBody: "Los eventos futuros de este calendario serán visibles para los miembros de la familia.", confirmShare: "Confirmar uso compartido", keepPrivate: "Mantener privado", addEvent: "Añadir evento", eventTitle: "Título del evento", calendar: "Calendario", useCalendar: "Usar el calendario {name}", saveEvent: "Guardar evento", deleteWarning: "¿Eliminar este evento? Es posible que los participantes dejen de tener acceso.", confirmDelete: "Confirmar eliminación", cancel: "Cancelar", deleteEvent: "Eliminar evento", records: "Registros", opening: "Abriendo Registros", loading: "Cargando tus archivadores privados.", binders: "Tus archivadores", createBinder: "Crear un archivador", binderBody: "Organiza registros privados por familia y menor.", binderName: "Nombre del archivador", childLabel: "Identificador del menor", creating: "Creando...", create: "Crear archivador", timeline: "Cronología privada", noSources: "Aún no hay fuentes vinculadas.", message: "Mensaje", calendarEvent: "Evento del calendario", timelineEntry: "Entrada de cronología: {kind}", linkMessage: "Vincular último mensaje", linkEvent: "Vincular próximo evento", attachment: "Preparar detalles del archivo adjunto", fileName: "Nombre original del archivo", mediaType: "Tipo de medio", fileSize: "Tamaño del archivo en bytes", preparing: "Preparando...", prepare: "Preparar detalles", prepared: "Detalles del archivo adjunto preparados", detailsPrepared: "Detalles preparados", noUpload: "No se subió ningún archivo.", archive: "Archivar archivador", tryAgain: "Intentar de nuevo", returnHome: "Volver al inicio", anotherTask: "Elige otra tarea.", binderNameError: "Introduce un nombre de archivador.", childLabelError: "Introduce un identificador del menor.", binderDetailsError: "Revisa los detalles del archivador.", attachmentDetailsError: "Revisa los detalles del archivo adjunto.", linkError: "PeacePad no pudo vincular esta fuente." }
} as const;

export type WorkflowKey = keyof typeof copy.en;
export function workflowText(locale: SupportedLocale, key: WorkflowKey, values?: Readonly<Record<string, string>>): string {
  const value = copy[locale][key];
  return values ? value.replace(/\{(\w+)\}/g, (token, name: string) => values[name] ?? token) : value;
}
